### ISSUE TITLE
テクスチャ画像のフィルタ処理に関して

### ISSUE THREAD

**Issue by qoopen0815** [Nishida-Lab/phoxi_ros_pkg#10]
お疲れ様です。

現在、箱にばら積みにされた点群のクラスタリングに取り組んでいるところです。
点群×画像のクラスタリングでも実装しようかね〜と考えているのですが、
今のシステムで流れているテクスチャ画像が以下のようになっており、
箱の中のパーツがほぼまっしろという状況です。

上記の問題を解決したく、
テクスチャ画像の画像処理に真面目に取り組んでみようと思います。
phoxi_img_converterで実装されていたコードを見直すとなかなかのウンコードでしたので、
[リファクタ](https://github.com/Nishida-Lab/phoxi_ros_pkg/pull/9)が済んだ後にでも進めようと思います。

![rgb_texture_screenshot_30 10 2019](https://user-images.githubusercontent.com/26988372/67871637-0464be00-fb74-11e9-9a81-b94901e0e786.png)

「助けて〜」的な内容ではないですがとりあえず報告しときます。

**Comment by qoopen0815** [comment]
良案あれば教えてや！

**Comment by MoriKen254** [comment]
お疲れ様です。

確か、生のテクスチャを一般のグレースケールにコンバートするノードがいたと思います。

その中で、マーカの検出精度を上げるために 画像全体の画素値を集計してcvequalizehistをかましたトピックをパブリッシュしていると思います。周辺の黒い領域とのコントラストを高めるため、白い領域の違いが視覚的には見づらくなっています。

画素値的にはきちんと差は残っていると思いますので、その差を強調できれは、いいですかね？差が明確な方が、画像処理は楽ではあります。

今度は、添付画像のバラ積み領域でROI (region of interest) を切った画像を生成し、その狭い領域中の画素値を集計してcpequalizehistをし直すのはいかが？

画素値操作をするとノイズはのるかもしれないので、消したければスムージングか、スパイクノイズであれば中央値プーリング等検討してみて下さい。どんな画像処理をするかによりますが。

一応アイデアとして、ご参考に。

**Comment by qoopen0815** [comment]
【フィルタ処理の現状】
生画像→ガンマ補正→コントラスト補正→出力
の処理を行うことで、以下のような結果になりました。

【生画像(topic : /photoneo_center/texture)】
![test](https://user-images.githubusercontent.com/26988372/68017971-54aa6000-fcdb-11e9-9464-1dd8f0821e94.png)

【ガンマ補正】
![rgb_texture_screenshot_01 11 2019](https://user-images.githubusercontent.com/26988372/68018092-9b985580-fcdb-11e9-82a4-8e8ee6f295ed.png)

【コントラスト調整】
![rgb_texture_screenshot_01 11 2019](https://user-images.githubusercontent.com/26988372/68018143-c387b900-fcdb-11e9-9c2d-1453dacb0cba.png)

【キャリブレーション実行結果】
問題なく動きました↓
![image](https://user-images.githubusercontent.com/26988372/68017612-73f4bd80-fcda-11e9-9134-9e8195ed4f47.png)

**Comment by qoopen0815** [comment]
ちなみにシステム全体で使用する画像の処理をこのノードの中だけですべて完結したいという考えはなく、それぞれの役割に合わせて画像を最適化してもいいと思っています。

**Comment by MoriKen254** [comment]
お疲れさまです！

>ちなみにシステム全体で使用する画像の処理をこのノードの中だけですべて完結したいという考えはなく、それぞれの役割に合わせて画像を最適化してもいいと思っています。

そのとおりです。変換する種別ごとにノード化しても良いと思います。そうすると、スーパクラスを作成し、filterImgだけを処理に合わせてオーバライドするという、基本的な継承プログラムを作りたくなりますね。これも、リファクタリングの一つです。

> 生画像→ガンマ補正→コントラスト補正→出力

ガンマ補正、良いですね！もう既にいい感じに見えますが、念の為確認してもいいですか？

今ガンマ=1/2.5 となっているとお見受けしましたが、ガンマ=2.5の方が白色領域のコントラストが強い画像になりませんか？それとも、やってみたら1/2.5の方がいい感じになったってことかな？

ガンマが1未満だと黒色領域(輝度値が0に近い領域)の感度を上げ、白色領域(輝度値が上限に近い領域)の感度を下げるのではないかな、と思いまして。

![image](https://user-images.githubusercontent.com/12078261/68021834-def7c180-fce5-11e9-8166-3471efa5776a.png)

今やりたいことは、白く塗りつぶされた感じの部品部分の輝度値の差異をより強調したいのかなと思ったので、つぶやいてみました。

よろしくお願いします。

**Comment by qoopen0815** [comment]
グラフわかりやすいですね。ありがとうございます

試しに逆数とってみました↓
![s](https://user-images.githubusercontent.com/26988372/68022593-21220280-fce8-11e9-9dda-28c5e14a9f6f.png)

真っ黒になりました。

**Comment by MoriKen254** [comment]
参った！ ＼(^o^)／

**Comment by MoriKen254** [comment]
課題は以下の4点。

- 複数の異なる用途に応じて、変換アルゴリズムを切り替えられるようにしたい。
- クラスによる階層化を行いたい。
- ROI を切ってヒストグラム調整する機能の追加。
- 変化ノードのサービス化。

これをそれぞれ、独立したissueで管理していきます。

**Comment by MoriKen254** [comment]
独立issue 立てました。

Close!
