### ISSUE TITLE
 CIが落ちている

### ISSUE THREAD

**Issue by MoriKen254** [Nishida-Lab/phoxi_ros_pkg#18]
https://gitlab.com/nishidalab/phoxi_ros_pkg/-/jobs/341950251

lintで落ちていますね。次からは、ローカルで catkin_lint を通してみましょう！

@calm0815 くんが最後にPRを出したと思うので、頑張って通してみて下さい。難しいエラーではありません。

@YamafukuKei くん、 @AtsukiYokota くん辺りは、同様のエラーを経験しているはずですので、分からないようでしたら、相談してみるといいと思います。

よろしくお願いします( ´ ▽ ` )

**Comment by qoopen0815** [comment]
ご指摘ありがとうございます。
修正しましたので確認おねがいします。

**Comment by MoriKen254** [comment]
レビュしました！あと一周で終わると思うので、頑張って下さい！😄

**Comment by qoopen0815** [comment]
解決したので閉じます
