### ISSUE TITLE
photoneo_center/rgb_imageのちらつきについて

### ISSUE THREAD

**Issue by G0mez-o** [Nishida-Lab/phoxi_ros_pkg#23]
Photoneoの1.2系のファームウェアを入れた状態でhttps://github.com/Nishida-Lab/denso_recognition/pull/83 で述べられているようなセットアップを行い、本リポジトリのブランチを1.2系対応の```Yamafuku/add_get_one_frame_srv```に切り替えた状態で以下のコマンド
```
PhoXiControl
```
```
roslaunch denso_bringup vs087_with_tercero_and_photoneo_bringup.launch
```
```
roslaunch phoxi_bringup phoxi_bringup.launch
```
を実行しrviz上で```photoneo_center/rgb_texture```を確認するとhttps://www.dropbox.com/s/1qdj0zx3a1rrdc2/rgb_texture_pub.m4v?dl=0
のような、2枚の異なる画像がpublishされているようなちらつきが発生します．
1.2系を使ったことがある@YamafukuKei ないし@AtsukiYokota の環境でも同様のことが起こっているのか、それとも僕の環境固有の現象なのか、教えてもらえると幸いです．

**Comment by YamafukuKei** [comment]
こちらでも同様の現象が起こります．

原因は，phoxi_camera と phoxi_ros_pkg 側でトピック名がかぶっているためです．かんたんにですが修正しておきます．

**Comment by G0mez-o** [comment]
https://github.com/Nishida-Lab/phoxi_ros_pkg/pull/24 にて解決したのでcloseします
ありがとうございました！
